services:
  - type: web
    name: visionflow-backend
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000

  - type: static
    name: visionflow-frontend
    region: oregon
    plan: free
    buildCommand: ""          # Leave this empty for HTML/CSS/JS
    staticPublishPath: frontend
